#ifndef HELLO_H
#define HELLO_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>

typedef struct HelloWorld {
  uint64_t value;
} HelloWorld;

void hello_world_free(HelloWorld *ptr);

HelloWorld *hello_world_new(uint64_t value);

#endif /* HELLO_H */
