[workspace]
members = ["hello-local", "hello-world"]
#members = ["world", "hello-world"]

exclude = ["hello", "world"]

#[patch."https://github.com/sammyne/rust-playground"]
#hello = { path = "hello-local" }